namespace Conquer.Game.Simulation;

/// <summary>
/// A real country a nation takes its name from, with real cities and regions (in Spanish, in the font's Latin-1 letters)
/// for the cities it founds and the provinces it claims: the best known first, so its first city is its capital.
/// </summary>
internal sealed record Country(string Name, string[] Cities, string[] Regions);

internal static class Countries
{
    public static readonly Country[] All =
    [
        new("España",
            ["Madrid", "Toledo", "Sevilla", "Barcelona", "Valencia", "Zaragoza", "Córdoba", "Granada", "Salamanca", "Burgos", "León", "Santiago",
             "Málaga", "Cádiz", "Bilbao", "Valladolid", "Pamplona", "Oviedo", "Segovia", "Ávila", "Murcia", "Cartagena", "Tarragona", "Mérida",
             "Badajoz", "Cáceres", "Almería", "Jaén", "Huesca", "Teruel", "Cuenca", "Soria", "Lugo", "Girona", "Lleida", "Alicante"],
            ["Castilla", "Aragón", "Andalucía", "Galicia", "Navarra", "Asturias", "Extremadura", "Cataluña", "La Mancha", "Vizcaya", "Rioja",
             "Cantabria", "El Bierzo", "La Alcarria", "Las Hurdes", "Ampurdán", "Maestrazgo", "Alpujarras", "Tierra de Campos", "La Sagra",
             "Monegros", "Penedés", "Montes de Toledo", "Sierra Morena", "Campo de Gibraltar", "Vega de Granada", "Somontano", "Gredos",
             "Valle del Ebro", "Costa Brava"]),
        new("Portugal",
            ["Lisboa", "Oporto", "Coímbra", "Braga", "Évora", "Faro", "Guimarães", "Aveiro", "Viseu", "Leiria", "Setúbal", "Beja", "Bragança",
             "Guarda", "Castelo Branco", "Santarém", "Tomar", "Lagos", "Sintra", "Viana do Castelo", "Portalegre", "Chaves", "Lamego", "Elvas"],
            ["Alentejo", "Algarve", "Beira", "Minho", "Trás-os-Montes", "Estremadura", "Ribatejo", "Douro", "Beira Alta", "Beira Baixa",
             "Beira Litoral", "Costa de Prata", "Serra da Estrela", "Barroso", "Oeste", "Alto Alentejo", "Baixo Alentejo", "Cávado", "Tâmega",
             "Dão", "Lafões", "Sado"]),
        new("Francia",
            ["París", "Lyon", "Marsella", "Burdeos", "Toulouse", "Nantes", "Estrasburgo", "Lille", "Reims", "Orleans", "Ruan", "Aviñón", "Niza",
             "Montpellier", "Dijon", "Tours", "Limoges", "Grenoble", "Nancy", "Metz", "Amiens", "Brest", "Rennes", "Poitiers", "Carcasona",
             "Perpiñán", "Bayona", "Calais", "Chartres", "Versalles", "Clermont", "Besanzón", "Arlés", "Nimes"],
            ["Normandía", "Bretaña", "Borgoña", "Provenza", "Aquitania", "Gascuña", "Champaña", "Picardía", "Lorena", "Alsacia", "Auvernia",
             "Languedoc", "Saboya", "Delfinado", "Turena", "Anjou", "Poitou", "Lemosín", "Berry", "Franco Condado", "Artois", "Rosellón",
             "Bearne", "Périgord", "Maine", "Nivernais", "Lionesado", "Vendée", "Cévennes", "Camarga"]),
        new("Inglaterra",
            ["Londres", "York", "Winchester", "Canterbury", "Oxford", "Cambridge", "Bristol", "Mánchester", "Liverpool", "Birmingham", "Leeds",
             "Newcastle", "Norwich", "Exeter", "Plymouth", "Southampton", "Nottingham", "Leicester", "Lincoln", "Chester", "Bath", "Durham",
             "Coventry", "Gloucester", "Worcester", "Hastings", "Dover", "Salisbury", "Carlisle", "Lancaster"],
            ["Wessex", "Mercia", "Northumbria", "Anglia Oriental", "Kent", "Sussex", "Essex", "Cornualles", "Devon", "Yorkshire", "Lancashire",
             "Cumbria", "Norfolk", "Suffolk", "Dorset", "Somerset", "Cotswolds", "Midlands", "Fens", "Peninos", "Chilterns", "Hampshire",
             "Wiltshire", "Shropshire", "Cheshire", "Northumberland", "Lake District", "Dartmoor"]),
        new("Escocia",
            ["Edimburgo", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Scone", "Stirling", "St Andrews", "Dunfermline", "Ayr", "Dumfries",
             "Oban", "Fort William", "Elgin", "Kirkwall", "Lerwick", "Paisley", "Falkirk", "Montrose", "Wick"],
            ["Highlands", "Lowlands", "Fife", "Lothian", "Galloway", "Argyll", "Caithness", "Sutherland", "Ross", "Moray", "Buchan", "Angus",
             "Lanark", "Ayrshire", "Borders", "Hébridas", "Orcadas", "Shetland", "Skye", "Lochaber", "Strathclyde", "Atholl", "Badenoch"]),
        new("Irlanda",
            ["Dublín", "Cork", "Galway", "Limerick", "Waterford", "Kilkenny", "Wexford", "Sligo", "Drogheda", "Dundalk", "Athlone", "Tralee",
             "Ennis", "Derry", "Belfast", "Armagh", "Killarney", "Clonmel", "Wicklow", "Mullingar"],
            ["Leinster", "Munster", "Connacht", "Úlster", "Meath", "Kerry", "Clare", "Donegal", "Mayo", "Tipperary", "Connemara", "Burren",
             "Ossory", "Tyrone", "Fermanagh", "Offaly", "Laois", "Roscommon", "Leitrim", "Antrim", "Down", "Louth"]),
        new("Alemania",
            ["Berlín", "Aquisgrán", "Colonia", "Múnich", "Hamburgo", "Fráncfort", "Núremberg", "Dresde", "Leipzig", "Bremen", "Hannover",
             "Stuttgart", "Maguncia", "Tréveris", "Worms", "Espira", "Ratisbona", "Augsburgo", "Lübeck", "Magdeburgo", "Erfurt", "Weimar",
             "Bonn", "Düsseldorf", "Dortmund", "Münster", "Kiel", "Rostock", "Friburgo", "Heidelberg", "Potsdam", "Brunswick"],
            ["Baviera", "Sajonia", "Prusia", "Turingia", "Suabia", "Franconia", "Westfalia", "Renania", "Hesse", "Brandeburgo", "Pomerania",
             "Mecklemburgo", "Holstein", "Baden", "Wurtemberg", "Palatinado", "Selva Negra", "Harz", "Frisia", "Lusacia", "Eifel", "Algovia",
             "Brisgovia", "Oldemburgo", "Lippe", "Hunsrück", "Spessart", "Vogtland"]),
        new("Italia",
            ["Roma", "Milán", "Venecia", "Florencia", "Nápoles", "Génova", "Turín", "Bolonia", "Palermo", "Pisa", "Siena", "Verona", "Padua",
             "Rávena", "Parma", "Módena", "Mantua", "Ferrara", "Bari", "Tarento", "Mesina", "Catania", "Siracusa", "Perusa", "Ancona", "Trieste",
             "Bérgamo", "Brescia", "Lucca", "Salerno", "Cagliari", "Trento", "Asís", "Urbino"],
            ["Lacio", "Toscana", "Lombardía", "Piamonte", "Véneto", "Liguria", "Emilia", "Romaña", "Umbría", "Las Marcas", "Abruzos", "Molise",
             "Campania", "Apulia", "Basilicata", "Calabria", "Sicilia", "Cerdeña", "Friuli", "Tirol", "Valle de Aosta", "Maremma", "Chianti",
             "Salento", "Ciociaria", "Langhe", "Polesine", "Garfagnana", "Sabina", "Irpinia"]),
        new("Países Bajos",
            ["Ámsterdam", "Róterdam", "La Haya", "Utrecht", "Leiden", "Haarlem", "Delft", "Groninga", "Maastricht", "Eindhoven", "Nimega",
             "Arnhem", "Breda", "Zwolle", "Leeuwarden", "Middelburg", "Dordrecht", "Gouda", "Alkmaar", "Deventer"],
            ["Holanda", "Zelanda", "Frisia Occidental", "Güeldres", "Brabante", "Limburgo", "Overijssel", "Drenthe", "Groninga Rural", "Flevo",
             "Veluwe", "Twente", "Betuwe", "Achterhoek", "Kennemerland", "Waterland", "Westland", "Salland"]),
        new("Flandes",
            ["Bruselas", "Brujas", "Gante", "Amberes", "Lovaina", "Lieja", "Namur", "Malinas", "Mons", "Tournai", "Ypres", "Ostende", "Charleroi",
             "Hasselt", "Kortrijk", "Dinant", "Arlon", "Spa", "Tongeren", "Aalst"],
            ["Brabante Valón", "Henao", "Hesbaye", "Ardenas", "Campine", "Condroz", "Famenne", "Gaume", "Pajottenland", "Waes", "Westhoek",
             "Hageland", "Meetjesland", "Fagne", "Luxemburgo"]),
        new("Suiza",
            ["Berna", "Zúrich", "Ginebra", "Basilea", "Lausana", "Lucerna", "San Galo", "Lugano", "Friburgo de Suiza", "Neuchâtel", "Sion",
             "Coira", "Schaffhausen", "Zug", "Thun", "Bienne", "Winterthur", "Interlaken", "Davos", "Locarno"],
            ["Valais", "Tesino", "Grisones", "Uri", "Schwyz", "Unterwalden", "Glaris", "Appenzell", "Turgovia", "Argovia", "Jura", "Vaud",
             "Oberland", "Emmental", "Engadina", "Toggenburgo", "Entlebuch"]),
        new("Austria",
            ["Viena", "Salzburgo", "Innsbruck", "Graz", "Linz", "Klagenfurt", "Bregenz", "Villach", "Wels", "Steyr", "Krems", "Melk", "Leoben",
             "Hallstatt", "Bad Ischl", "Kufstein", "Feldkirch", "Eisenstadt", "Baden bei Wien", "Wiener Neustadt"],
            ["Estiria", "Carintia", "Tirol del Norte", "Vorarlberg", "Burgenland", "Alta Austria", "Baja Austria", "Wachau", "Salzkammergut",
             "Mühlviertel", "Waldviertel", "Weinviertel", "Pinzgau", "Pongau", "Montafon", "Zillertal", "Ötztal"]),
        new("Polonia",
            ["Varsovia", "Cracovia", "Gdansk", "Poznan", "Breslavia", "Lodz", "Lublin", "Torun", "Szczecin", "Bydgoszcz", "Katowice", "Czestochowa",
             "Gniezno", "Plock", "Radom", "Kielce", "Rzeszów", "Tarnów", "Olsztyn", "Bialystok", "Zamosc", "Sandomierz", "Elblag", "Opole"],
            ["Mazovia", "Pequeña Polonia", "Gran Polonia", "Silesia", "Masuria", "Podlaquia", "Cuyavia", "Pomerelia", "Varmia", "Podhale",
             "Subcarpacia", "Kashubia", "Chelmno", "Tatras", "Bieszczady", "Polesia", "Roztocze", "Jura Polaco"]),
        new("Bohemia",
            ["Praga", "Brno", "Ostrava", "Pilsen", "Olomouc", "Liberec", "Budweis", "Hradec Králové", "Pardubice", "Kutná Hora", "Tábor",
             "Karlsbad", "Jihlava", "Znojmo", "Cheb", "Kolín", "Zlín", "Opava", "Trebic", "Litomerice"],
            ["Moravia", "Silesia Checa", "Sudetes", "Bosque de Bohemia", "Krkonose", "Valaquia Morava", "Haná", "Chodsko", "Podripsko",
             "Slovácko", "Polabí", "Vysocina", "Posumaví", "Jeseníky"]),
        new("Hungría",
            ["Budapest", "Esztergom", "Székesfehérvár", "Debrecen", "Szeged", "Pécs", "Gyor", "Miskolc", "Eger", "Sopron", "Kecskemét",
             "Nyíregyháza", "Szombathely", "Veszprém", "Kalocsa", "Szolnok", "Tokaj", "Visegrád", "Kaposvár", "Vác"],
            ["Transdanubia", "Gran Llanura", "Alföld", "Puszta", "Balaton", "Bakony", "Mátra", "Bükk", "Somogy", "Zala", "Baranya", "Tolna",
             "Nyírség", "Hortobágy", "Kiskunság", "Jászság", "Cumania", "Hajdúság"]),
        new("Suecia",
            ["Estocolmo", "Uppsala", "Gotemburgo", "Malmö", "Lund", "Kalmar", "Visby", "Västerås", "Örebro", "Linköping", "Norrköping",
             "Jönköping", "Gävle", "Umeå", "Luleå", "Kiruna", "Sundsvall", "Karlstad", "Halmstad", "Helsingborg", "Växjö", "Falun"],
            ["Uppland", "Gotland", "Escania", "Esmolandia", "Dalarna", "Laponia", "Norrland", "Värmland", "Västergötland", "Östergötland",
             "Södermanland", "Halland", "Blekinge", "Jämtland", "Hälsingland", "Ångermanland", "Bohuslän", "Öland", "Närke", "Dalsland"]),
        new("Noruega",
            ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø", "Kristiansand", "Ålesund", "Bodø", "Drammen", "Hamar", "Lillehammer",
             "Molde", "Narvik", "Hammerfest", "Arendal", "Tønsberg", "Fredrikstad", "Kongsberg", "Røros", "Alta"],
            ["Vestland", "Trøndelag", "Nordland", "Finnmark", "Telemark", "Agder", "Rogaland", "Hordaland", "Sogn", "Fjordane", "Hedmark",
             "Oppland", "Buskerud", "Østfold", "Vestfold", "Lofoten", "Valdres", "Gudbrandsdal", "Hallingdal", "Romsdal"]),
        new("Dinamarca",
            ["Copenhague", "Aarhus", "Odense", "Aalborg", "Roskilde", "Ribe", "Esbjerg", "Viborg", "Helsingør", "Randers", "Kolding", "Vejle",
             "Horsens", "Silkeborg", "Svendborg", "Nyborg", "Haderslev", "Skagen", "Thisted", "Næstved"],
            ["Jutlandia", "Selandia", "Fionia", "Lolland", "Falster", "Bornholm", "Himmerland", "Vendsyssel", "Thy", "Mors", "Djursland",
             "Salling", "Langeland", "Møn", "Schleswig"]),
        new("Finlandia",
            ["Helsinki", "Turku", "Tampere", "Oulu", "Vaasa", "Kuopio", "Jyväskylä", "Lahti", "Pori", "Joensuu", "Rovaniemi", "Kotka",
             "Hämeenlinna", "Porvoo", "Savonlinna", "Kajaani", "Kokkola", "Rauma", "Mikkeli", "Lappeenranta"],
            ["Carelia", "Savonia", "Tavastia", "Ostrobotnia", "Uusimaa", "Satakunta", "Kainuu", "Laponia Finlandesa", "Åland", "Kymenlaakso",
             "Päijänne", "Pirkanmaa", "Finlandia Propia", "Kuusamo"]),
        new("Rusia",
            ["Moscú", "Nóvgorod", "San Petersburgo", "Vladímir", "Súzdal", "Tver", "Pskov", "Riazán", "Smolensk", "Kazán", "Nizhni Nóvgorod",
             "Yaroslavl", "Kostromá", "Tula", "Oriol", "Kursk", "Vorónezh", "Sarátov", "Samara", "Astracán", "Volgogrado", "Perm", "Ekaterimburgo",
             "Omsk", "Tomsk", "Irkutsk", "Arcángel", "Vólogda", "Múrmansk", "Kaliningrado", "Rostov"],
            ["Moscovia", "Ingria", "Carelia Rusa", "Siberia", "Urales", "Volga", "Kubán", "Don", "Tartaria", "Bashkiria", "Mordovia", "Chuvasia",
             "Komi", "Pomoria", "Mesheria", "Zalesie", "Severia", "Tierra Negra", "Baskunchak", "Altái", "Taimir", "Yakutia", "Buriatia",
             "Kamchatka", "Primorie", "Chukotka", "Kola", "Daguestán"]),
        new("Ucrania",
            ["Kiev", "Leópolis", "Járkov", "Odesa", "Dnipró", "Chernígov", "Poltava", "Vínnytsia", "Zhytómyr", "Jersón", "Mykolaiv", "Zaporiyia",
             "Sumy", "Ternópil", "Lutsk", "Rivne", "Ivano-Frankivsk", "Uzhgorod", "Chernivtsí", "Kamianets"],
            ["Galitzia", "Volinia", "Podolia", "Zaporozhia", "Crimea", "Rutenia", "Bucovina", "Slobodá", "Donbás", "Tauria", "Polesia Ucraniana",
             "Pokutia", "Transcarpatia", "Budjak", "Siveria"]),
        new("Grecia",
            ["Atenas", "Esparta", "Tebas", "Corinto", "Argos", "Delfos", "Olimpia", "Micenas", "Tesalónica", "Pela", "Larisa", "Patras",
             "Heraclión", "Cnosos", "Rodas", "Éfeso", "Mileto", "Siracusa Griega", "Megara", "Eretria", "Calcis", "Ioánina", "Kavala", "Volos"],
            ["Ática", "Beocia", "Peloponeso", "Laconia", "Mesenia", "Arcadia", "Élide", "Acaya", "Argólide", "Tesalia", "Macedonia", "Epiro",
             "Etolia", "Fócide", "Eubea", "Creta", "Cícladas", "Dodecaneso", "Tracia", "Calcídica", "Jonia", "Eólida", "Lesbos", "Quíos"]),
        new("Turquía",
            ["Estambul", "Ankara", "Esmirna", "Bursa", "Konya", "Antalya", "Adana", "Trebisonda", "Edirne", "Kayseri", "Sivas", "Erzurum",
             "Diyarbakir", "Gaziantep", "Samsun", "Sinope", "Iznik", "Pérgamo", "Troya", "Mardin", "Malatya", "Urfa", "Van", "Tarso"],
            ["Anatolia", "Bitinia", "Frigia", "Lidia", "Caria", "Licia", "Panfilia", "Cilicia", "Capadocia", "Galacia", "Ponto", "Paflagonia",
             "Misia", "Pisidia", "Licaonia", "Isauria", "Armenia Menor", "Comagene", "Tracia Oriental", "Tauro", "Kurdistán", "Lazistán"]),
        new("Rumanía",
            ["Bucarest", "Cluj", "Iasi", "Timisoara", "Brasov", "Sibiu", "Constanza", "Craiova", "Galati", "Oradea", "Arad", "Pitesti",
             "Ploiesti", "Suceava", "Targoviste", "Alba Iulia", "Sighisoara", "Bacau", "Braila", "Tulcea"],
            ["Valaquia", "Moldavia", "Transilvania", "Dobruja", "Banato", "Oltenia", "Muntenia", "Maramures", "Crisana", "Bucovina del Sur",
             "Carpatos", "Delta del Danubio", "Tara Barsei", "Hateg"]),
        new("Serbia",
            ["Belgrado", "Novi Sad", "Nis", "Kragujevac", "Subotica", "Kraljevo", "Smederevo", "Pec", "Prizren", "Valjevo", "Uzice", "Pozarevac",
             "Leskovac", "Zrenjanin", "Sabac", "Cacak", "Novi Pazar", "Vranje", "Sombor", "Pancevo"],
            ["Sumadija", "Voivodina", "Raska", "Kosovo", "Metohija", "Banat Serbio", "Backa", "Srem", "Macva", "Pomoravlje", "Timok", "Zlatibor",
             "Kopaonik", "Podunavlje"]),
        new("Bulgaria",
            ["Sofía", "Plovdiv", "Varna", "Burgas", "Tarnovo", "Ruse", "Stara Zagora", "Pleven", "Shumen", "Preslav", "Vidin", "Sliven",
             "Jaskovo", "Pernik", "Kazanlak", "Sozopol", "Nesebar", "Blagoevgrad", "Lovech", "Gabrovo"],
            ["Mesia", "Tracia Superior", "Ródope", "Pirin", "Rila", "Balcanes", "Dobruja del Sur", "Ludogorie", "Strandzha", "Sredna Gora",
             "Shopluk", "Valle de las Rosas"]),
        new("Egipto",
            ["El Cairo", "Alejandría", "Tebas Egipcia", "Menfis", "Luxor", "Asuán", "Guiza", "Damieta", "Rosetta", "Suez", "Port Said",
             "Ismailía", "Asiut", "Minia", "Sohag", "Qena", "Tanis", "Bubastis", "Heliópolis", "Abydos", "Edfu", "Siwa"],
            ["Bajo Egipto", "Alto Egipto", "Delta", "Fayum", "Sinaí", "Nubia", "Tebaida", "Desierto Occidental", "Desierto Oriental", "Mar Rojo",
             "Kharga", "Dakhla", "Bahariya", "Farafra", "Wadi Natrun"]),
        new("Marruecos",
            ["Rabat", "Fez", "Marrakech", "Mequinez", "Casablanca", "Tánger", "Tetuán", "Agadir", "Uxda", "Esauira", "Larache", "Arcila",
             "Chauen", "Taza", "Safí", "Uarzazat", "Nador", "Alhucemas", "Kenitra", "Erfud"],
            ["Rif", "Atlas Medio", "Alto Atlas", "Antiatlas", "Sus", "Draa", "Tafilalet", "Garb", "Chauía", "Haouz", "Doukkala", "Yebala",
             "Oriental", "Zemmour", "Tadla"]),
        new("Etiopía",
            ["Adís Abeba", "Aksum", "Gondar", "Lalibela", "Harar", "Bahir Dar", "Dire Dawa", "Mekele", "Adua", "Dessie", "Jimma", "Awasa",
             "Debre Markos", "Arba Minch", "Gambela", "Nekemte", "Debre Berhan", "Shashamane"],
            ["Tigray", "Amhara", "Shewa", "Gojjam", "Wollo", "Begemder", "Oromía", "Sidamo", "Kaffa", "Ogaden", "Afar", "Bale", "Arsi", "Ilubabor",
             "Wollega", "Gamo"]),
        new("Malí",
            ["Tombuctú", "Gao", "Djenné", "Bamako", "Mopti", "Ségou", "Kayes", "Sikasso", "Kidal", "Niani", "Koulikoro", "San", "Bandiagara",
             "Kangaba", "Nioro", "Kita"],
            ["Sahel", "Níger Interior", "Macina", "Dogón", "Adrar de los Ifoghas", "Azawad", "Kaarta", "Bambuk", "Wagadu", "Bélédougou",
             "Mandé", "Gourma"]),
        new("Persia",
            ["Teherán", "Isfahán", "Shiraz", "Tabriz", "Mashhad", "Persépolis", "Susa", "Ecbatana", "Hamadán", "Kermán", "Yazd", "Qom", "Kashán",
             "Ahvaz", "Rasht", "Kermanshah", "Bam", "Nishapur", "Sari", "Zanjan", "Ardabil", "Bushehr"],
            ["Fars", "Media", "Partia", "Jorasán", "Kermania", "Juzestán", "Azerbaiyán", "Guilán", "Mazandarán", "Hircania", "Elam", "Carmania",
             "Sistán", "Baluchistán", "Luristán", "Kurdistán Persa", "Zagros", "Dasht-e Kavir", "Golestán", "Kuhistán"]),
        new("Arabia",
            ["La Meca", "Medina", "Riad", "Yeda", "Taif", "Dammam", "Hofuf", "Tabuk", "Hail", "Abha", "Yanbu", "Buraidah", "Najrán", "Jizán",
             "Sakaka", "Al Ula", "Diriyah", "Qatif"],
            ["Hiyaz", "Nechd", "Asir", "Tihama", "Al Hasa", "Rub al-Jali", "Nefud", "Yamama", "Qasim", "Jabal Shammar", "Hadramaut", "Dahna",
             "Wadi Sirhan", "Midián"]),
        new("India",
            ["Delhi", "Agra", "Bombay", "Calcuta", "Madrás", "Benarés", "Lahore", "Jaipur", "Hyderabad", "Bangalore", "Lucknow", "Patna",
             "Ahmedabad", "Pune", "Surat", "Mysore", "Goa", "Cochin", "Madurai", "Amritsar", "Udaipur", "Jodhpur", "Bhopal", "Nagpur", "Indore",
             "Gwalior", "Kanpur", "Allahabad", "Pataliputra", "Ujjain"],
            ["Bengala", "Punyab", "Rajputana", "Guyarat", "Decán", "Maharashtra", "Bihar", "Orissa", "Malabar", "Coromandel", "Cachemira",
             "Assam", "Awadh", "Malwa", "Bundelkhand", "Doab", "Konkan", "Carnatic", "Telingana", "Kerala", "Sind", "Thar", "Ganges", "Himachal",
             "Garhwal", "Sundarbans", "Nilgiris", "Kutch"]),
        new("China",
            ["Pekín", "Nankín", "Xi'an", "Luoyang", "Kaifeng", "Hangzhou", "Cantón", "Shanghái", "Chengdu", "Wuhan", "Changsha", "Suzhou",
             "Tianjin", "Chongqing", "Kunming", "Fuzhou", "Xiamen", "Jinan", "Taiyuan", "Shenyang", "Harbin", "Lanzhou", "Datong", "Anyang",
             "Qufu", "Yangzhou", "Ningbo", "Guilin", "Nanchang", "Hefei", "Dunhuang", "Lhasa"],
            ["Shandong", "Henan", "Hebei", "Shanxi", "Shaanxi", "Gansu", "Sichuan", "Yunnan", "Guizhou", "Hunan", "Hubei", "Jiangxi", "Jiangsu",
             "Zhejiang", "Fujian", "Guangdong", "Guangxi", "Anhui", "Manchuria", "Xinjiang", "Tíbet", "Qinghai", "Mongolia Interior", "Ningxia",
             "Hainan", "Liaodong", "Jiangnan", "Lingnan"]),
        new("Japón",
            ["Kioto", "Tokio", "Osaka", "Nara", "Kamakura", "Edo", "Nagoya", "Kobe", "Hiroshima", "Nagasaki", "Sendai", "Sapporo", "Fukuoka",
             "Kanazawa", "Kagoshima", "Kumamoto", "Okayama", "Himeji", "Matsue", "Niigata", "Shizuoka", "Hakodate", "Nikko", "Yokohama"],
            ["Kanto", "Kansai", "Tohoku", "Chubu", "Chugoku", "Shikoku", "Kyushu", "Hokkaido", "Yamato", "Musashi", "Owari", "Mino", "Echigo",
             "Kai", "Satsuma", "Choshu", "Tosa", "Mutsu", "Dewa", "Shinano", "Izumo", "Bizen", "Hizen", "Higo", "Settsu", "Omi"]),
        new("Corea",
            ["Seúl", "Pyongyang", "Busan", "Gyeongju", "Kaesong", "Daegu", "Gwangju", "Daejeon", "Incheon", "Suwon", "Jeonju", "Chuncheon",
             "Hamhung", "Wonsan", "Chongjin", "Sinuiju", "Ulsan", "Jinju", "Andong", "Mokpo"],
            ["Gyeonggi", "Chungcheong", "Jeolla", "Gyeongsang", "Gangwon", "Hwanghae", "Pyongan", "Hamgyong", "Jeju", "Baekje", "Silla",
             "Goguryeo", "Gaya", "Tamna"]),
        new("Vietnam",
            ["Hanói", "Hue", "Saigón", "Hai Phong", "Da Nang", "Hoi An", "Nha Trang", "Can Tho", "Vinh", "Nam Dinh", "Thanh Hoa", "Quy Nhon",
             "Dalat", "My Tho", "Lang Son", "Dien Bien", "Ha Long", "Phan Thiet"],
            ["Tonkín", "Annam", "Cochinchina", "Delta del Mekong", "Delta del Río Rojo", "Altiplano Central", "Champa", "Thanh Nghe",
             "Viet Bac", "Tay Bac", "Phu Yen", "Binh Dinh"]),
        new("Siam",
            ["Bangkok", "Ayutthaya", "Sukhothai", "Chiang Mai", "Lopburi", "Phitsanulok", "Nakhon Ratchasima", "Ubon", "Udon", "Phuket",
             "Songkhla", "Nakhon Si Thammarat", "Chiang Rai", "Lampang", "Nan", "Pattani", "Kanchanaburi", "Ratchaburi"],
            ["Lanna", "Isan", "Llanura Central", "Siam Meridional", "Tenasserim", "Korat", "Chao Phraya", "Mekong Siamés", "Andamán", "Golfo"]),
        new("Indonesia",
            ["Yakarta", "Surabaya", "Bandung", "Semarang", "Yogyakarta", "Medan", "Palembang", "Makassar", "Malang", "Surakarta", "Denpasar",
             "Banda Aceh", "Padang", "Manado", "Ambon", "Pontianak", "Banjarmasin", "Kupang", "Jayapura", "Bogor"],
            ["Java", "Sumatra", "Borneo", "Célebes", "Bali", "Molucas", "Lombok", "Flores", "Timor", "Sumbawa", "Madura", "Aceh", "Minangkabau",
             "Sunda", "Banten", "Mataram", "Majapahit", "Papúa"]),
        new("Mongolia",
            ["Ulán Bator", "Karakórum", "Erdenet", "Darján", "Choibalsan", "Jovd", "Ölgii", "Murun", "Uliastai", "Bayanhongor", "Sainshand",
             "Dalanzadgad", "Arvaikheer", "Tsetserleg", "Zuunmod", "Baruun-Urt"],
            ["Gobi", "Altái Mongol", "Jangai", "Jentii", "Orjón", "Selenga", "Jövsgöl", "Dornod", "Dzungaria", "Ordos", "Tuvá", "Uvs"]),
        new("Australia",
            ["Sídney", "Melbourne", "Brisbane", "Perth", "Adelaida", "Hobart", "Darwin", "Canberra", "Newcastle de Australia", "Geelong",
             "Townsville", "Cairns", "Ballarat", "Bendigo", "Launceston", "Toowoomba", "Wollongong", "Alice Springs", "Broome", "Kalgoorlie"],
            ["Nueva Gales del Sur", "Victoria", "Queensland", "Tasmania", "Australia Meridional", "Australia Occidental", "Territorio del Norte",
             "Kimberley", "Pilbara", "Outback", "Gippsland", "Riverina", "Nullarbor", "Tierra de Arnhem", "Cabo York", "Montañas Azules"]),
        new("México",
            ["Tenochtitlan", "Puebla", "Guadalajara", "Monterrey", "Veracruz", "Oaxaca", "Mérida de Yucatán", "Querétaro", "Morelia", "Zacatecas",
             "Guanajuato", "San Luis Potosí", "Acapulco", "Durango", "Chihuahua", "Saltillo", "Tlaxcala", "Cholula", "Taxco", "Campeche",
             "Teotihuacán", "Toluca", "Cuernavaca", "Hermosillo"],
            ["Anáhuac", "Yucatán", "Bajío", "Huasteca", "Mixteca", "Sonora", "Sinaloa", "Jalisco", "Michoacán", "Chiapas", "Tabasco", "Nayarit",
             "Coahuila", "Nuevo León", "Tamaulipas", "Guerrero", "Baja California", "Sierra Madre", "Soconusco", "Istmo"]),
        new("Perú",
            ["Cuzco", "Lima", "Arequipa", "Trujillo", "Cajamarca", "Ayacucho", "Puno", "Piura", "Chiclayo", "Huancayo", "Iquitos", "Tacna",
             "Ica", "Huánuco", "Chachapoyas", "Moquegua", "Nazca", "Huaraz", "Tumbes", "Abancay"],
            ["Collao", "Chinchaysuyo", "Antisuyo", "Contisuyo", "Collasuyo", "Altiplano", "Callejón de Huaylas", "Valle Sagrado", "Amazonía Peruana",
             "Costa Norte", "Mantaro", "Apurímac", "Madre de Dios", "Titicaca"]),
        new("Argentina",
            ["Buenos Aires", "Córdoba de Tucumán", "Rosario", "Mendoza", "Tucumán", "Salta", "La Plata", "Santa Fe", "Mar del Plata", "Bahía Blanca",
             "Paraná", "Corrientes", "Jujuy", "San Juan", "Neuquén", "Bariloche", "Ushuaia", "Posadas", "Resistencia", "Santiago del Estero"],
            ["Pampa", "Patagonia", "Cuyo", "Chaco", "Mesopotamia", "Puna", "Gran Chaco", "Tierra del Fuego", "Litoral", "Quebrada de Humahuaca",
             "Valles Calchaquíes", "Llanos Riojanos", "Misiones", "Comahue", "Santa Cruz"]),
        new("Brasil",
            ["Río de Janeiro", "São Paulo", "Salvador", "Recife", "Belém", "Manaos", "Brasilia", "Belo Horizonte", "Porto Alegre", "Curitiba",
             "Fortaleza", "São Luís", "Olinda", "Ouro Preto", "Florianópolis", "Natal", "Vitória", "Goiânia", "Cuiabá", "Santos", "Campinas",
             "Petrópolis"],
            ["Amazonia", "Nordeste", "Sertão", "Minas Gerais", "Bahía", "Pernambuco", "Mato Grosso", "Goiás", "Paraná Brasileño", "Río Grande",
             "Santa Catarina", "Pará", "Maranhão", "Ceará", "Pantanal", "Cerrado", "Recôncavo", "Espírito Santo"]),
        new("Colombia",
            ["Bogotá", "Medellín", "Cali", "Cartagena de Indias", "Barranquilla", "Santa Marta", "Popayán", "Tunja", "Pasto", "Bucaramanga",
             "Cúcuta", "Manizales", "Pereira", "Ibagué", "Neiva", "Villavicencio", "Montería", "Mompox"],
            ["Cundinamarca", "Antioquia", "Boyacá", "Santander", "Valle del Cauca", "Cauca", "Nariño", "Tolima", "Huila", "Llanos Orientales",
             "Chocó", "Guajira", "Magdalena", "Caldas", "Sierra Nevada"]),
        new("Chile",
            ["Santiago de Chile", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Iquique", "Temuco", "Valdivia", "Puerto Montt",
             "Punta Arenas", "Arica", "Talca", "Chillán", "Rancagua", "Copiapó", "Osorno", "Calama", "Coquimbo"],
            ["Atacama", "Araucanía", "Chiloé", "Magallanes", "Aysén", "Norte Chico", "Norte Grande", "Valle Central", "Biobío", "Maule",
             "Los Lagos", "Tarapacá", "Aconcagua"]),
        new("Estados Unidos",
            ["Washington", "Nueva York", "Filadelfia", "Boston", "Chicago", "Nueva Orleans", "San Francisco", "Los Ángeles", "San Luis", "Baltimore",
             "Charleston", "Savannah", "Atlanta", "Denver", "Seattle", "Detroit", "Pittsburgh", "Richmond", "Santa Fe de Nuevo México", "San Antonio",
             "Houston", "Memphis", "Nashville", "Cincinnati", "Albany", "Portland", "Miami", "Salt Lake City", "Kansas City", "Omaha"],
            ["Nueva Inglaterra", "Virginia", "Carolina", "Georgia", "Florida", "Luisiana", "Texas", "California", "Oregón", "Ohio", "Kentucky",
             "Tennessee", "Pensilvania", "Míchigan", "Illinois", "Misuri", "Kansas", "Nebraska", "Dakota", "Montana", "Wyoming", "Colorado",
             "Nevada", "Arizona", "Nuevo México", "Apalaches", "Grandes Llanuras", "Mojave", "Ozark", "Adirondack"]),
        new("Canadá",
            ["Quebec", "Montreal", "Toronto", "Ottawa", "Halifax", "Vancouver", "Winnipeg", "Calgary", "Edmonton", "Regina", "Saskatoon",
             "Victoria de Canadá", "San Juan de Terranova", "Fredericton", "Charlottetown", "Kingston", "Hamilton", "Thunder Bay", "Whitehorse",
             "Yellowknife"],
            ["Ontario", "Quebec Rural", "Acadia", "Nueva Escocia", "Nuevo Brunswick", "Terranova", "Labrador", "Manitoba", "Saskatchewan",
             "Alberta", "Columbia Británica", "Yukón", "Nunavut", "Klondike", "Gaspesia", "Muskoka", "Rocosas"]),
    ];

    /// <summary>The country of this name; null for a nation named otherwise (saved games from before the real names).</summary>
    public static Country? ByName(string name) => All.FirstOrDefault(c => c.Name == name);

    /// <summary>Distinct, saturated colours that read well over every biome, for the first nations.</summary>
    private static readonly uint[] BaseColors =
    [
        0xFFD03A3A, 0xFF2F6FDB, 0xFFE8C21E, 0xFF8E3FD1, 0xFFEE7A1E, 0xFF1FB5A8, 0xFFE0569B, 0xFF7A5230,
        0xFF6CC83B, 0xFF3AC7E8, 0xFFB0B0B0, 0xFF2E2E8F,
    ];

    /// <summary>
    /// The colour of the nth nation: the base colours first, then hues spread by the golden angle at alternating
    /// lightness, so every new one stands as far as it can from those before it.
    /// </summary>
    public static uint Color(int n)
    {
        if (n < BaseColors.Length) return BaseColors[n];
        int k = n - BaseColors.Length;
        double hue = (k * 137.508 + 15) % 360;
        double lightness = (k % 3) switch { 0 => 0.42, 1 => 0.58, _ => 0.32 };
        double saturation = k % 2 == 0 ? 0.75 : 0.55;
        return FromHsl(hue, saturation, lightness);
    }

    private static uint FromHsl(double h, double s, double l)
    {
        double c = (1 - Math.Abs(2 * l - 1)) * s, x = c * (1 - Math.Abs(h / 60 % 2 - 1)), m = l - c / 2;
        var (r, g, b) = (int)(h / 60) switch
        {
            0 => (c, x, 0.0),
            1 => (x, c, 0.0),
            2 => (0.0, c, x),
            3 => (0.0, x, c),
            4 => (x, 0.0, c),
            _ => (c, 0.0, x),
        };
        uint Byte(double v) => (uint)Math.Round((v + m) * 255);
        return 0xFF000000 | (Byte(r) << 16) | (Byte(g) << 8) | Byte(b);
    }

    /// <summary>As many countries as there are nations, in random order.</summary>
    public static List<Country> Pick(int count, Random random) =>
        All.OrderBy(_ => random.Next()).Take(count).ToList();

    public static int MaxNations => All.Length;
}
