using Conquer.Game.Military;
using Conquer.Game.Rules;
using Conquer.Game.World;

namespace Conquer.Presentation;

/// <summary>
/// The in-game help, topic by topic. Figures come from the rules, so the help follows any rebalancing.
/// In the text, "## " starts a heading and "- " a bullet (see <see cref="Markup"/>).
/// </summary>
public static class HelpTopics
{
    public static readonly (string Title, string[] Text)[] All =
    [
        ("Controles",
        [
            "## Ratón",
            "- Clic izquierdo: selecciona una unidad o una provincia; sobre unas espadas rojas, abre la batalla.",
            "- Clic derecho: mueve la unidad seleccionada. Sobre una provincia enemiga con tropas, la ataca; sobre una flota tuya en el mar de al lado, embarca.",
            "- Arrastrar: mueve el mapa. Rueda: zoom.",
            "## Teclado",
            "- Espacio: pausa o reanuda. 1 a 5: velocidad del tiempo.",
            "- W A S D o las flechas: mueven el mapa. + y -: zoom.",
            "- Tab: cambia el modo de mapa. Inicio: centra el mapa en tu capital.",
            "- N: pantalla de la nación. F1: esta ayuda. Esc: cierra ventanas, quita la selección o abre el menú.",
        ]),
        ("Primeros pasos",
        [
            $"Empiezas con {GameRules.StartingCitizens:N0} colonos y nada de tierra. Busca una provincia fértil (mejor junto a un gran río) y pulsa «Fundar ciudad»: será tu capital.",
            "## Qué hacer después",
            $"- Bajo las alertas, una tarjeta te propone el siguiente objetivo (fundar la capital, investigar, construir, entrenar exploradores, reclamar tierra, una segunda ciudad...) y cómo cumplirlo; «Ir» te lleva adonde se hace. Cada uno da {GameRules.ObjectiveGold:0} de oro. Puedes plegarla con «-».",
            "- En la pantalla de la nación (N), pestaña Ciencia, elige qué investigar en cada rama.",
            "- Debajo de la barra superior aparecen alertas cuando algo necesita atención (hambre, descontento, tropas sin suministro o pasando frío, obras terminadas, ciencia sin elegir...). Pasa el ratón por encima para ver qué pasa y haz clic para ir allí.",
            "- Entrena exploradores en la ciudad (baratos y rápidos) y reclama con ellos las provincias libres de alrededor: los colonos de tus ciudades irán a vivir allí solos. Solo reclaman las unidades con al menos un batallón de exploradores. Con «Explorar y reclamar», una unidad de exploradores lo hace por su cuenta: va a la mejor provincia libre junto a tus fronteras, la reclama y sigue con la siguiente. Con «Explorar», solo descubre: va a la tierra desconocida más cercana, y luego a la siguiente, sin reclamar nada ni entrar en tierras enemigas.",
            $"- El mar, el hielo polar y las cumbres (por encima de {GameRules.PeakElevation:N0} m, una sola provincia por cordillera) no se pueden reclamar. Las tropas cruzan el hielo y las cumbres, despacio.",
            "- Construye granjas y aserraderos, y una ciudad nueva donde haya 500 habitantes.",
            "- Envía colonos desde una ciudad para fundar otras más lejos.",
            "## Consejo",
            "Vigila la comida en la barra superior: si se acaba, la gente muere de hambre y la moral se hunde.",
        ]),
        ("Población y moral",
        [
            "Cada provincia tiene habitantes, moral (0 a 100) y fertilidad. Cada una tiene sus propios nacimientos según su fertilidad, sus habitantes y la tierra que tiene, mientras haya comida y sitio; las ciudades crecen el doble de rápido. La población crece despacio (unos pocos por ciento al año), y cada era la tierra alimenta a más gente: el doble en la Medieval, ocho veces más en la Moderna.",
            $"La comida almacenada se estropea: cada día se pierde el {GameRules.FoodSpoilage:P0} de lo guardado.",
            "## Moral",
            $"- Sube con la ciudad (+{GameRules.CityMood:0}), la capital (+{GameRules.CapitalMood:0}), las reservas de comida, las fiestas (+{GameRules.FestivalMood:0} durante {GameRules.FestivalDays} días), templos, anfiteatros y avances.",
            $"- Baja con la distancia a la capital (hasta -{GameRules.MaxDistanceMoodPenalty:0}), el hacinamiento, el hambre ({GameRules.StarvingMood:0}), la ocupación enemiga, la cultura extranjera y otra fe.",
            $"- Por debajo de {GameRules.UnrestMood:0} la provincia está descontenta y no paga impuestos. Una moral alta hace trabajar más.",
            "## Cultura y rebelión",
            $"- La gente conserva la cultura de la nación que la pobló. Bajo otro dueño pierde hasta {GameRules.ForeignCultureMood:0} de moral, menos a medida que se asimila (unos {GameRules.AssimilationYears:0} años, menos con moral alta; los migrantes de tus otras provincias ayudan).",
            $"- Una provincia descontenta sin tropas tuyas dentro se acerca a la rebelión (en {GameRules.RevoltDays / 2:0} a {GameRules.RevoltDays:0} días, antes cuanto peor la moral). Si su gente es de una nación que aún existe, se une a ella; si no, hay una revuelta: muere parte de la gente y arde un edificio.",
            "- Una guarnición (un regimiento en la provincia) detiene la rebelión. El panel de la provincia muestra cómo va.",
            "## Religión",
            $"- Cada nación sigue una fe: {string.Join(", ", Religions.Names)}. La gente de cada provincia conserva la de quien la pobló.",
            $"- Bajo un dueño de otra fe pierde {GameRules.OtherFaithMood:0} de moral hasta convertirse, en unos {GameRules.ConversionYears:0} años: más deprisa con moral alta, con un templo (el doble) y con la Teología.",
            $"- Las naciones de la misma fe se ven mejor (+{GameRules.SameFaithOpinion:0}) y las de otra, peor ({GameRules.OtherFaithOpinion:0}). El modo de mapa Religión muestra la fe de cada provincia.",
            "## Epidemias",
            $"- De vez en cuando una ciudad enferma, más cuanto más grande es. Durante {GameRules.PlagueDays} días la epidemia mata al {GameRules.PlagueDeathRate:P1} de su gente cada día y le quita {GameRules.PlagueMood:0} de moral.",
            "- Se contagia a las provincias vecinas, mucho más por los caminos, y de un puerto a otros cercanos.",
            $"- La Medicina, la Salubridad, los Antibióticos, los herbolarios y los hospitales la frenan (hasta un {GameRules.MaxPlagueResistance:P0}). Al pasar, la provincia queda inmune unos {GameRules.PlagueImmunityYears:0} años.",
            "## Decisiones",
            $"- Alguna vez al año pasa algo en una de tus provincias (una sequía, un filón de oro, refugiados, bandidos, una gran cosecha, un inventor) y se abre una ventana para que decidas. El tiempo se para hasta que respondes.",
            $"- Cada respuesta tiene su precio: comida u oro, gente o moral. Lo que está en juego crece con tu nación. La moral que cambia dura un año.",
            $"- Si no respondes en {GameRules.DecisionDays} días, se elige la primera respuesta. Los rivales también deciden las suyas.",
            "## Migración",
            "Las ciudades envían gente a tus provincias poco pobladas. Puedes forzar una migración pagando oro, pero los migrantes llegan descontentos.",
        ]),
        ("Economía y recursos",
        [
            "Tus provincias producen comida y madera, y pagan oro en impuestos. Todo va al almacén de la nación (barra superior). La pestaña Almacén de la nación (N) dice, recurso a recurso, cuánto hay y cuánto entró y salió el último día: producción, comercio, consumo, ejército y talleres.",
            "## Yacimientos",
            "- Piedra, carbón, hierro, cobre, azufre, salitre, oro, plata, silicio, petróleo, aluminio y caucho salen de yacimientos: bolsas finitas que se agotan. Los caballos salen de pastos, que no se agotan.",
            "- Al empezar solo conoces la piedra, los caballos, el cobre, el oro y la plata; los demás los revelan los avances (Minería el carbón, Trabajo del hierro el hierro, Pólvora el azufre y el salitre, Química el caucho...).",
            "- La piedra levanta templos, acueductos, anfiteatros, murallas, castillos, universidades y bancos; hay canteras en casi todas las colinas y montañas. El salitre y el azufre hacen la pólvora: los piden las armas de pólvora, los cañones y la artillería, y los fusiles y las armas modernas, el salitre. El azufre abunda en montañas y desiertos, y el salitre en los desiertos; fuera de ellos escasean.",
            "- Los caballos, de los pastos de praderas, estepas y sabanas, los piden la caballería (uno por jinete) y los carros de guerra.",
            $"- Un yacimiento rinde al máximo con {GameRules.DepositFullWorkers:N0} habitantes en su provincia. El modo de mapa Recursos los muestra.",
            "## Edificios",
            "En la pestaña Edificios de cada provincia. Granjas, graneros, aserraderos y minas van en cualquier provincia habitada; el resto, solo en ciudades. Cada edificio pide un avance.",
            "## Carreteras y ferrocarriles",
            "- Los construyen tus ingenieros: desde una ciudad o un cuartel general tuyos, pulsa «Construir carretera» en su panel y elige qué otra ciudad o cuartel unir (el más cercano sale elegido).",
            "- La ruta es la que seguiría un ejército, por tu tierra, la que ocupas o la libre; las ciudades por las que pasa quedan unidas también. Solo se pagan los tramos que faltan.",
            "- Cada batallón de ingenieros en la ruta hace un día de trabajo al día; si se van, la obra se para. Se ven en el mapa: la carretera clara, el ferrocarril oscuro con traviesas.",
            $"- Por ellas se marcha más deprisa y llega el suministro: a todo lo que unen a tus ciudades y, desde ahí, hasta {MilitaryRules.SupplyRangeHours / 24:0} días de marcha.",
        ]),
        ("Ciudades",
        [
            "Las ciudades producen ciencia, crecen más deprisa, entrenan tropas y construyen los mejores edificios.",
            $"- Con colonos: «Fundar ciudad» en una provincia libre o tuya.",
            $"- Sin colonos: en la pestaña Edificios de una provincia tuya con al menos {GameRules.CityBuildingPopulation} habitantes aparece «Ciudad» ({GameRules.CityCost}, {GameRules.CityBuildingDays} días).",
            "- No puede haber dos ciudades juntas. Tú eliges el nombre.",
        ]),
        ("Ciencia",
        [
            "La ciencia de tus ciudades avanza en tres ramas a la vez: Economía, Sociedad y Militar. En la pestaña Ciencia (N) eliges qué investigar en cada una.",
            "## Prioridades",
            $"- Cada rama tiene una prioridad de 0 a {GameRules.MaxResearchPriority}: la ciencia se reparte en proporción.",
            "- Una rama sin nada elegido cede su parte a las demás; si ninguna investiga, la ciencia se guarda para el siguiente avance que elijas.",
            "## Niveles y eras",
            "- Cada nivel se abre al conocer uno de los avances del nivel anterior de su rama. Algunos avances piden otros concretos.",
            "- Los niveles se agrupan en eras: Antigüedad, Clásica, Medieval, Descubrimientos, Industrial y Moderna. Arriba de la pestaña hay un botón por era.",
            $"- Cada nación vecina que ya conoce un avance te lo abarata un {GameRules.NeighbourResearchDiscount:P0}.",
            "## Instituciones",
            $"- Cada era nueva tiene una institución (Urbanismo, Feudalismo, Humanismo, Industrialización, Electrificación) que nace en algún lugar del mundo y se extiende de provincia en provincia.",
            $"- Tu nación la adopta cuando la tiene la mitad de tu población, o antes pagando oro. Da un bonus; mientras no la adoptes, los avances de su era cuestan un {GameRules.InstitutionPenalty:P0} más.",
            "- El modo de mapa Instituciones muestra por dónde van.",
        ]),
        ("Ejército",
        [
            "Las unidades de combate se forman con batallones entrenados en las ciudades (pestaña Ejército de la provincia). Los hombres salen de la ciudad.",
            "## Tipos de batallón",
            "- El ejército tiene cuatro grupos: infantería, caballería, artillería y apoyo. Cada grupo tiene sus líneas, y cada línea un modelo por época que llega con su avance:",
            "- Infantería ligera: guerreros, vélites, arcabuceros e infantería ligera. Infantería pesada: espadachines, falanges, legionarios, infantería pesada y piqueros; con el Estriado pasa a infantería ligera.",
            "- Infantería a distancia: arqueros, ballesteros, mosqueteros, fusileros y ametralladores. Tropas de montaña (desde la era Clásica, mejores en cada era) y paracaidistas (con la Aviación).",
            "- Caballería: jinetes, catafractos, caballeros y caballería mecanizada. Carros de guerra y, con los Blindados, tanques.",
            "- Artillería: catapultas, trabuquetes, cañones, artillería de campaña y artillería pesada; y la antiaérea, con la Aviación.",
            "- Apoyo: exploradores (50 hombres), ingenieros (100) y médicos (50).",
            "- Al descubrir un modelo nuevo, tus batallones de esa línea lo adoptan cuando les llega su equipo (ver Equipo).",
            $"- Las tropas de montaña luchan un {MilitaryRules.MountainTroopsRoughTerrain - 1:P0} mejor en montañas, colinas, bosques y pantanos. Los médicos no combaten, pero salvan un {MilitaryRules.MedicsSaving:P0} de las bajas de su unidad.",
            $"- La antiaérea dispara ×{MilitaryRules.AntiAirAgainstAircraft:0} contra los aviones y cada batallón suyo quita un {MilitaryRules.AntiAirShield:P0} a su fuego (hasta un {MilitaryRules.MaxAntiAirShield:P0}).",
            "## Equipo",
            "- Cada batallón necesita el equipo de su modelo: un arma por hombre, un caballo por jinete, 5 catapultas (con 50 hombres) o 10 tanques (con 50). Toda la infantería de una época comparte sus armas (armas antiguas, clásicas, medievales, de pólvora, fusiles y armas modernas), y exploradores, ingenieros y médicos, los suministros, uno por hombre. Se ve en la pestaña Almacén de la nación (N), y lo que necesita cada tipo de batallón, en la pestaña Unidades.",
            $"- Lo fabrican los talleres y las fábricas: en la pestaña Edificios de su provincia eliges qué hace cada uno. Un taller hace en los días de instrucción de un batallón el equipo de uno; una fábrica, el doble. Gasta los recursos del batallón salvo el oro; si faltan, fabrica menos o nada.",
            "- El equipo va al almacén de la nación. Entrenar un batallón lo toma de allí y solo cuesta el oro; se entrena con el modelo más moderno del que haya equipo. Sin equipo, no se entrena.",
            "- Reforzar las bajas también gasta equipo, y un batallón con suministro adopta un modelo nuevo cuando le llega su equipo desde la capital: devuelve el viejo al almacén. Si el modelo nuevo usa las mismas armas (de falanges a legionarios), lo adopta al momento.",
            $"- Empiezas con equipo para {MilitaryRules.StartingWarriorKits} batallones de guerreros y {MilitaryRules.StartingScoutKits} de exploradores. El taller se puede construir desde el principio.",
            "## Reclutas",
            $"- Solo se alistan los hombres que hay en la reserva de reclutas: {GameRules.BaseManpower:N0} más el {GameRules.ManpowerShare:P0} de tu población (Instrucción militar y Servicio militar obligatorio la agrandan). Entrenar batallones y barcos, formar cuarteles generales y reforzar unidades la gastan; licenciar una unidad devuelve sus hombres.",
            $"- Se rellena despacio: de vacía a llena en {GameRules.ManpowerRecoveryYears:0} años. Perder un ejército duele. El Resumen de la nación y la pestaña Ejército dicen cuántos quedan.",
            "## Cuartel y taller",
            "- Solo las provincias con cuartel entrenan tropas de combate. Exploradores, ingenieros, médicos, colonos y cuarteles generales se forman en cualquier ciudad; los barcos, en los puertos.",
            "- Las máquinas de guerra (toda la artillería, la antiaérea, los tanques y los bombarderos) no salen del cuartel sino del taller. Una plantilla que mezcla soldados y máquinas pide los dos.",
            "- Con la Industrialización, tus talleres pasan a ser fábricas: siguen construyendo las máquinas de guerra, fabrican el doble de equipo y además dan +50 % de madera y de yacimientos. Desde entonces se construyen fábricas en lugar de talleres.",
            "- El cuartel, el taller y la fábrica se pueden levantar en cualquier provincia tuya, tenga ciudad o no: una provincia sin ciudad con uno de ellos entrena tropas (pestaña Ejército) y siempre conserva algunos habitantes.",
            $"- Los avances militares que estudian una tropa (Arcos mejorados, Cría caballar, Talleres de asedio...) hacen que el cuartel o el taller la entrene un {MilitaryRules.TechTrainingSpeed:P0} antes, y se suman. Arcos mejorados, por ejemplo, solo acelera a la infantería a distancia.",
            "## Organización",
            $"- Regimiento: hasta {MilitaryRules.MaxBattalionsPerRegiment} batallones. Brigada: hasta {MilitaryRules.MaxRegimentsPerBrigade} regimientos. División: hasta {MilitaryRules.MaxDivisionParts} brigadas y regimientos, y nunca más de {MilitaryRules.MaxDivisionMen:N0} hombres. Cada una es una sola ficha en el mapa, que se mueve y combate entera.",
            "- Diseña plantillas de regimiento en la pestaña Plantillas de la nación para entrenarlos enteros de golpe.",
            "- El botón «Editar unidad» de su panel abre una ventana para renombrarla, elegir su oficial y organizarla con las demás de la provincia:",
            "- «Unir» junta los batallones de dos regimientos en uno. «Incorporar» mete una unidad en otra: dos regimientos forman una brigada; un regimiento entra en una brigada; dos brigadas, o una brigada llena y un regimiento, forman una división; una división acoge regimientos y brigadas.",
            "- «Separar» saca una parte (un regimiento de una brigada, una brigada o un regimiento de una división) como unidad propia, con su número y su nombre. También puedes marcar batallones sueltos y separarlos como un regimiento nuevo.",
            "- El rango de su oficial va con su tamaño: coronel para un regimiento, brigadier para una brigada y general de división para una división.",
            "- Por encima están los cuarteles generales: Cuerpo, Ejército y Grupo de ejércitos. Dan un bonus en combate a las unidades bajo su mando que estén a su alcance.",
            "## Mantenimiento",
            $"- Cada día, batallones, barcos y cuarteles cuestan un {MilitaryRules.UpkeepGoldShare:P0} de su oro y un {MilitaryRules.UpkeepResourceShare:P0} de sus demás recursos (la madera no).",
            "- Si no hay con qué pagar, las tropas pierden organización, desertan y no se recuperan.",
            "## Oficiales y experiencia",
            $"- Recluta oficiales con oro ({MilitaryRules.OfficerCost:0}) en la ventana de edición de una unidad: van a la reserva de tu nación y desde ahí los pones al mando.",
            "- Su rango va con el tamaño de lo que mandan: Coronel (regimiento), Brigadier (brigada), General de división (división), Teniente general (cuerpo), General (ejército) y Mariscal (grupo de ejércitos). Ascienden solos cuando su unidad crece.",
            "- Hay tres armas, cada una con sus nombres para los mismos rangos: el ejército manda regimientos y cuarteles; la armada, las flotas (capitán de navío, comodoro, contraalmirante, vicealmirante, almirante y gran almirante); y la aviación, los regimientos de aviones (coronel de aviación, general de brigada aérea, general de división aérea, teniente general del aire, general del aire y mariscal del aire). Solo un oficial del arma de la unidad puede mandarla. Los de marina piden una flota o un puerto, y los de aviación, la Aviación.",
            "- El oficial de una flota aplica sus rasgos y su habilidad al fuego de sus barcos, y gana estrellas con las victorias en el mar.",
            "- Cada oficial tiene una o dos virtudes (ofensivo, defensivo, organizador, táctico, marchador, intendente), que mejoran con sus estrellas, y a veces un defecto (timorato, temerario, desorganizado, indeciso, lento, corrupto).",
            "- El oficial de una unidad de combate le aplica sus rasgos; el general de un cuartel, a las unidades bajo su mando que estén a su alcance.",
            $"- Tienen de 1 a {Officer.MaxSkill} estrellas y ganan una cada {Officer.VictoriesPerStar} victorias. Si su unidad es destruida en combate, caen con ella; si la relevas o la unes a otra, vuelven a la reserva.",
            $"- Los batallones ganan experiencia combatiendo (Novato, Regular, Veterano, Élite): hasta +{MilitaryRules.ExperienceBonus:P0} de fuego. Los reclutas nuevos la diluyen.",
            "## Suministro y combate",
            "- Las tropas se abastecen desde tus ciudades y por tus carreteras y ferrocarriles, a través de tierra propia o libre; sin suministro pierden hombres y organización.",
            "## Logística",
            "- El almacén de la nación está en su capital. Cada día la capital envía a cada unidad de combate con suministro lo que le falta: reclutas para reforzarla con su equipo, el equipo del modelo nuevo para modernizarla y la munición que ha gastado.",
            "- Los envíos tardan lo que se tarda en llegar desde la capital por la red de suministro (más deprisa por carreteras y ferrocarriles), o por mar desde uno de tus puertos si hace falta cruzarlo: entonces van en convoyes (ver Flotas y mar). El panel de la unidad dice qué le llega y cuándo, y la pestaña Almacén, lo que va en camino. Si al llegar la unidad está aislada o ya no existe, vuelve al almacén.",
            "- Cuando no hay para todos, se sirve primero a las unidades de los cuarteles generales de prioridad alta, luego normal y luego baja (elígela en el panel del cuartel). Las unidades sin cuartel a su alcance van las últimas y sus envíos tardan el doble. Un cuartel aislado deja a sus unidades sin envíos.",
            $"- Munición: cada unidad lleva suministros para {MilitaryRules.AmmoHours:0} horas de combate. Cada batallón que combate gasta {MilitaryRules.AmmoPerHundredMenHour:0.##} por cada 100 hombres y hora; sin munición lucha al {MilitaryRules.OutOfAmmoEfficiency:P0}. Fabrica suministros en los talleres para reponerla.",
            "## Estaciones",
            $"- Lejos del trópico, en invierno la nieve frena a las tropas (hasta el doble de tiempo) y el frío se lleva hasta un {GameRules.WinterAttrition:P1} de sus hombres al día, salvo si se refugian en una de tus ciudades. De diciembre a febrero es invierno en el norte y verano en el sur.",
            $"- En primavera y otoño, el barro las frena algo menos. El desierto desgasta todo el año, y también las cumbres y el hielo polar (un {GameRules.PeakAttrition:P1} al día) y la alta montaña (un {GameRules.HighMountainAttrition:P1}).",
            "- La fecha de arriba dice la estación en tu capital; el panel de cada provincia, la de allí. El mapa de terreno se cubre de nieve en invierno.",
            "- Mover una unidad a una provincia enemiga con tropas la ataca; sin tropas, la ocupa. Cada hora ambos bandos se dañan; el que pierde la organización se retira.",
            $"- Frente: solo combaten a la vez los mejores batallones que caben en él ({MilitaryRules.FrontWidth(Biome.Grassland)} en llano, {MilitaryRules.FrontWidth(Biome.HighMountains)} en alta montaña); el resto espera en reserva.",
            "- La artillería, la aviación y los ingenieros van detrás del frente (la mitad de ancho) y reciben menos daño. Los médicos se quedan atrás y no reciben daño.",
            $"- Si el atacante lleva ingenieros, el río no le frena y la ventaja del terreno del defensor se queda en la {MilitaryRules.EngineeredTerrainDefense:P0}.",
            $"- Armas combinadas: cada tipo de tropa distinto (infantería, caballería, artillería, blindados, aviación, ingenieros) suma +{MilitaryRules.CombinedArmsBonus:P0} de fuego, hasta +{MilitaryRules.MaxCombinedArmsBonus:P0}.",
            "- Defender es más fácil en montañas, bosques, ríos y detrás de murallas o castillos. La caballería rinde menos en terreno difícil.",
            $"- Asedios: una provincia con murallas o castillo no se ocupa al entrar; hay que sitiarla {MilitaryRules.SiegeDaysPerDefense / 2:0} días (murallas) o {MilitaryRules.SiegeDaysPerDefense:0} (castillo). Catapultas, cañones y artillería lo acortan. Si los sitiadores se van, el asedio se levanta; mientras sitian, reciben suministro si la provincia linda con una tuya abastecida.",
        ]),
        ("Aviación",
        [
            "Los aviones no son fichas en el mapa: forman alas que despegan de aeródromos y portaaviones.",
            "## Tipos y épocas",
            "- Cazas (dominan el aire), apoyo cercano (bombardean tropas en batalla), bombarderos estratégicos (ciudades e industria), aviación naval (flotas y convoyes) y transportes (paracaidistas).",
            "- Cada tipo tiene tres modelos: biplanos con Aviación, monoplanos con Radar y reactores con Motor a reacción. Cada época vuela más lejos y pega más fuerte.",
            "## Aeródromos y alas",
            $"- Construye un Aeródromo (Aviación) en cualquier provincia tuya: alberga {MilitaryRules.WingsPerAirfield} alas. Cada ala son {MilitaryRules.PlanesPerWing} aviones, que fabrican los talleres y las fábricas como el resto del equipo.",
            "- Forma las alas con los botones de aviones de la pestaña Ejército del aeródromo; el panel de la provincia muestra las que tiene.",
            $"- En su base, si tiene suministro, un ala recupera organización y repone aviones del almacén y tripulaciones de la reserva. Cada portaaviones lleva {MilitaryRules.WingsPerCarrier} alas de cazas, apoyo cercano o aviación naval, y si se hunde caen con él.",
            "- Un ala puede cambiar de base a otro aeródromo con sitio o a un portaaviones a menos del doble de su alcance. Si pierde su base, vuela al aeródromo tuyo más cercano con sitio; si no hay, se pierde.",
            "## Misiones",
            $"- En el panel del aeródromo (o del portaaviones) eliges la misión de cada ala y la provincia sobre la que vuela, a su alcance: cubre las provincias a menos de {MilitaryRules.MissionRadiusKm:N0} km. Con menos del {MilitaryRules.MinFlyingOrganisation:P0} de organización no despega.",
            $"- Superioridad aérea (cazas): quien tiene al menos el {MilitaryRules.AirRuleShare:P0} de los cazas sobre una provincia domina su cielo. Sus tropas luchan hasta un {MilitaryRules.AirSuperiorityBonus:P0} mejor y las enemigas peor; las tropas bajo un cielo enemigo marchan más despacio y reciben menos suministro. El panel de la provincia dice quién domina.",
            "- Apoyo cercano: suma su fuego a tus batallas de la zona. Bombardeo estratégico: quita moral a la provincia enemiga, frena sus talleres y puede derribar edificios. Ataque naval: daña las flotas enemigas y hunde convoyes en los mares de la zona.",
            $"- Bajo un cielo enemigo, los bombarderos, el apoyo cercano y la aviación naval hacen la mitad ({MilitaryRules.UnescortedBomberEffect:P0}). Cada día las alas enemigas que se cruzan se derriban aviones, y la antiaérea dispara a los que atacan su zona.",
            "- Paracaidistas: una unidad solo de paracaidistas en un aeródromo con aviones de transporte puede lanzarse («Lanzar en paracaídas...» en su panel) sobre una provincia sin tropas enemigas a su alcance; si es enemiga, la ocupa.",
        ]),
        ("Flotas y mar",
        [
            "Las tropas no cruzan el mar solas: necesitan barcos. Solo los aviones vuelan sobre él.",
            "## Puertos y barcos",
            "- Construye un Puerto (Navegación a vela) en una ciudad con costa. Allí se construyen los barcos, y cada uno forma una flota.",
            "- Los barcos se encargan a una cola de toda la nación, en la pestaña Marina (N) o desde la pestaña Ejército de un puerto. Cada puerto tiene una grada, y otra más con Dique seco; cada grada libre toma el primer barco de la cola que puede construir.",
            "- Cada día una grada avanza su barco y gasta la parte de su coste que toca a ese día; si no hay bastante, avanza solo lo que puede pagar. Al terminar, el barco toma su tripulación del puerto y de la reserva de reclutas y sale como una flota nueva. En la pestaña Marina puedes adelantar, retrasar o cancelar los encargos (lo gastado en uno cancelado se pierde).",
            "- Como el ejército, la marina tiene líneas con un modelo por época: transportes (barco de transporte, carraca, vapor y buque de transporte), que llevan tropas; buques de línea (trirreme, galeón, navío de línea, acorazado y acorazado moderno), los cañones de la flota; escoltas (liburna, carabela, fragata, crucero y destructor), ligeras y rápidas; submarinos, y portaaviones. Los más avanzados piden un Dique seco.",
            $"- Una flota en uno de tus puertos moderniza cada día sus barcos al modelo más nuevo de su línea que conozcas, pagando el {MilitaryRules.RefitCostShare:P0} de lo que cuesta: conserva su tripulación y el puerto completa el resto. El panel de la flota dice qué barcos pueden modernizarse.",
            "- Las flotas navegan por el mar costero con Navegación a vela y por el océano con Cartografía. Se reparan en puerto.",
            "## Transportar tropas",
            "- Embarca una unidad con el botón «Embarcar en...» de su panel o con clic derecho sobre una flota tuya con transportes en el mar de al lado.",
            "- Mueve la flota y, con la unidad embarcada seleccionada, haz clic derecho en la costa para desembarcar. En tierra enemiga sin tropas, la ocupa.",
            "- Las flotas enemigas que se encuentran combaten; la que se rompe huye o se hunde con lo que lleva.",
            "## Convoyes",
            $"- Lo que la capital envía a tus tropas al otro lado del mar viaja en convoyes: cada uno lleva {MilitaryRules.ConvoyCapacity:0} hombres, piezas o suministros. Se encargan en lotes de {MilitaryRules.ConvoysPerOrder} a los astilleros (pestaña Marina), y los que van en un envío no sirven para otro hasta que llega. Sin convoyes bastantes, los envíos por mar llevan menos.",
            $"- Las flotas enemigas que atacan convoyes en un mar de la ruta, o en uno vecino, hunden cada día parte de los convoyes y de su carga; los submarinos, el doble. Tus flotas que escoltan esos mares reducen mucho las pérdidas.",
            "## Misiones de las flotas",
            "- En el panel de una flota eliges su misión, que cumple donde está: Patrullar (va a por las flotas enemigas que entren en los mares vecinos), Escoltar convoyes (protege los tuyos en ese mar y los vecinos), Atacar convoyes (hunde los del enemigo en ese mar y los vecinos) o Bloquear puertos.",
            "- Un puerto enemigo junto a una flota que lo bloquea no construye barcos, no envía nada por mar y pierde los impuestos de su comercio marítimo.",
        ]),
        ("Diplomacia",
        [
            "En la pestaña Diplomacia de la nación declaras la guerra, propones la paz, firmas alianzas y haces regalos.",
            "- Tus ejércitos solo entran en tierras de naciones con las que estás en guerra, de tus aliados, de tus vasallos o de quien te deja pasar.",
            "- La puntuación de guerra (de -100 a 100) suma lo que ocupas del enemigo, resta lo que te ocupa y cuenta las batallas ganadas y perdidas. Las ciudades y la capital valen más.",
            "- Paz blanca: las provincias ocupadas vuelven a sus dueños. Los rivales la aceptan si la guerra les va mal o se alarga.",
            "- Exigir: te quedas con lo que ocupas, si la puntuación lo paga. Si te quedas con todo, la nación desaparece.",
            "- Ceder: entregas lo que te ocupan para acabar una guerra perdida.",
            $"- Tributo ({GameRules.ReparationsWarScore:0} de puntuación): te paga el {GameRules.ReparationsShare:P0} de sus ingresos de oro durante {GameRules.ReparationsDays / 365} años.",
            $"- Vasallo ({GameRules.VassalWarScore:0} de puntuación): te paga el {GameRules.VassalTributeShare:P0} de sus ingresos de oro, entra en tus guerras (y tú en las suyas si lo atacan), no declara guerras ni se alía con nadie, y sus tierras están abiertas a tus ejércitos. A los {GameRules.VassalAnnexYears:0} años puedes anexionarlo; también puedes liberarlo.",
            "- Capitulación: una nación en guerra que tiene todas sus ciudades ocupadas se rinde. Cada enemigo se queda con lo que ocupa, quien tiene su capital se lleva el resto, y la nación desaparece.",
            $"- Tras cada paz hay una tregua de {GameRules.TruceDays} días: ninguno de los dos puede declarar la guerra al otro.",
            $"- Opinión: cada nación piensa algo de las demás (de -100 a 100), por lo que ve (frontera, enemigos o rivales comunes, su gente bajo otro dueño) y por lo que recuerda (guerras, provincias quitadas, regalos), que se olvida con el tiempo. La columna Opinión dice qué piensan de ti y por qué.",
            $"- Alianzas: si uno de los aliados es atacado, los demás entran en la guerra, y sus ejércitos cruzan las tierras del otro. Los rivales aceptan si su opinión de ti llega a {GameRules.AllianceAcceptOpinion:0}; un regalo (un mes de tus ingresos de oro) la sube {GameRules.GiftOpinion:0}.",
            $"- Pacto de no agresión: ninguno de los dos puede declarar la guerra al otro. Si uno lo rompe, hay {GameRules.BrokenPactTruceDays} días de tregua y el otro lo recuerda. Los rivales lo firman si no te tienen manía ({GameRules.PactAcceptOpinion:0} de opinión), o desde {GameRules.FearedPactOpinion:0} si tu ejército es más fuerte. Un aliado con un pacto con el atacante no entra en la guerra.",
            $"- Paso militar: «Pedir paso» deja a tus ejércitos cruzar sus tierras (aceptan si su opinión de ti llega a {GameRules.AccessAcceptOpinion:0}); «Dar paso» deja a los suyos cruzar las tuyas y les gusta (+{GameRules.AccessOpinion:0}). Se retira cuando quieras y termina con la guerra.",
            "- Los rivales atacan a vecinos que creen poder vencer, más aún si se han quedado sin tierra libre, si el vecino ya está en otra guerra o si gobierna gente de su cultura.",
            $"- Comercio (pestaña Comercio): cada nación en paz vende la mitad de lo que gana al día de un recurso, por oro o por algo que te sobra a ti y le falta a ella, y te compra lo que te sobra. Cada recurso tiene un valor en oro; los rivales se quedan un margen de hasta el {GameRules.MaxTradeMargin:P0}, menor cuanto mejor te ven. Los acuerdos duran {GameRules.TradeDealDays} días (como mucho {GameRules.MaxTradeDeals} por nación), suben la opinión de los dos y se rompen si alguien no puede pagar o entregar, o con la guerra.",
            "- Con puertos y transportes, también cruzan el mar: reúnen tropas en su mayor puerto, embarcan y desembarcan en tu costa peor defendida. Con Navegación a vela llegan a costas cercanas; con Cartografía, al otro lado del océano.",
        ]),
        ("Mapa",
        [
            "Los botones de abajo (o Tab) cambian el modo de mapa:",
            "- Terreno y Político: el mundo y quién es dueño de cada provincia.",
            "- Población, Moral y Fertilidad: el estado de cada provincia habitada.",
            "- Recursos: los yacimientos que conoces, con un filtro por recurso. De cerca, cada provincia muestra los iconos de todos sus yacimientos; de lejos, el color del principal.",
            "- Instituciones: por dónde se han extendido.",
            "- Cultura: de qué nación es la gente de cada provincia. Si el color no es el de la franja de su frontera, la gente es extranjera.",
            "- Religión: la fe de la gente de cada provincia.",
            "Niebla de guerra: solo ves las tropas ajenas en tus tierras y las que ocupas, en las de tus aliados, tu señor y tus vasallos, en una provincia alrededor de todo ello y alrededor de tus unidades (los exploradores ven una más). Lo que exploraste pero ya no ves queda en gris; el resto del mundo, que nunca has visto, está en negro: ni su tierra, ni sus ciudades, ni sus dueños.",
            "Al pasar el ratón por una provincia verás sus datos. Las espadas rojas marcan batallas, en tierra o en el mar: haz clic en ellas para ver la batalla en detalle.",
        ]),
        ("Partida",
        [
            "- El menú (Esc o botón Menú) pausa el juego, guarda la partida y muestra el historial de versiones.",
            "- Opciones (en la pantalla inicial y en el menú de pausa): volumen de la música y del sonido de cuarto en cuarto (con - y +), animaciones sí o no, y el mapa con figuras 3D o con fichas OTAN. Se recuerdan entre partidas. La música cambia con la era y cuando estás en guerra.",
            "- La dificultad se elige al empezar: cambia cuántos yacimientos hay y su tamaño, los recursos iniciales y lo que producen los rivales.",
            "- Los rivales del ordenador se expanden, investigan, construyen y hacen la guerra por su cuenta.",
            $"- Estadísticas (pestaña de la nación): cada {GameRules.HistoryDays} días se anotan la población, el ejército, el oro y la ciencia al día y las provincias de cada nación; la gráfica muestra cómo han cambiado desde el principio de la partida.",
            "## Victoria y derrota",
            "- Dominación: gana quien haga caer a todas las demás naciones o las convierta en sus vasallas.",
            "- Ciencia: gana quien descubra todos los avances.",
            $"- Puntuación: si nadie ha ganado antes, al empezar el año {GameRules.ScoreVictoryYear} gana la nación con más puntos (uno por cada {GameRules.ScorePeople:N0} habitantes, {GameRules.ScorePerProvince:0} por provincia, {GameRules.ScorePerCity:0} por ciudad y {GameRules.ScorePerTech:0} por avance).",
            "- Pierdes si gana otra nación o si la tuya cae. En los dos casos puedes seguir jugando (o mirando). El Resumen de la nación muestra tu puntuación y lo cerca que estás de cada victoria.",
        ]),
    ];

    /// <summary>Every topic title and line of text, for checking them.</summary>
    public static IEnumerable<string> AllText => All.SelectMany(t => t.Text.Prepend(t.Title));

    /// <summary>A topic's text as headings, bullets and paragraphs.</summary>
    public static IReadOnlyList<MarkupLine> Lines(int topic) => All[topic].Text.Select(Markup.Parse).ToList();
}
