using Conquer.Game.Military;
using Conquer.Game.Rules;
using Conquer.Game.World;

namespace Conquer.Presentation;

/// <summary>
/// The in-game help, topic by topic. Figures come from the rules, so the help follows any rebalancing.
/// In the text, "## " starts a heading and "- " a bullet (see <see cref="Markup"/>).
/// </summary>
public static class HelpTopics
{
    public static readonly (string Title, string[] Text)[] All =
    [
        ("Controles",
        [
            "## Ratón",
            "- Clic izquierdo: selecciona una unidad o una provincia; sobre unas espadas rojas, abre la batalla.",
            "- Clic derecho: mueve la unidad seleccionada. Sobre una provincia enemiga con tropas, la ataca; sobre una flota tuya en el mar de al lado, embarca.",
            "- Arrastrar: mueve el mapa. Rueda: zoom.",
            "## Teclado",
            "- Espacio: pausa o reanuda. 1 a 5: velocidad del tiempo.",
            "- W A S D o las flechas: mueven el mapa. + y -: zoom.",
            "- Tab: cambia el modo de mapa. Inicio: centra el mapa en tu capital.",
            "- N: pantalla de la nación. F1: esta ayuda. Esc: cierra ventanas, quita la selección o abre el menú.",
        ]),
        ("Primeros pasos",
        [
            $"Empiezas con {GameRules.StartingCitizens:N0} colonos y nada de tierra. Busca una provincia fértil (mejor junto a un gran río) y pulsa «Fundar ciudad»: será tu capital.",
            "## Qué hacer después",
            "- En la pantalla de la nación (N), pestaña Ciencia, elige qué investigar en cada rama.",
            "- Debajo de la barra superior aparecen alertas cuando algo necesita atención (hambre, descontento, tropas sin suministro o pasando frío, ciencia sin elegir...). Pasa el ratón por encima para ver qué pasa y haz clic para ir allí.",
            "- Entrena exploradores en la ciudad (baratos y rápidos) y reclama con ellos las provincias libres de alrededor: los colonos de tus ciudades irán a vivir allí solos. Solo reclaman las unidades con al menos un batallón de exploradores. Con «Explorar y reclamar», una unidad de exploradores lo hace por su cuenta: va a la mejor provincia libre junto a tus fronteras, la reclama y sigue con la siguiente.",
            $"- El mar, el hielo polar y las cumbres (por encima de {GameRules.PeakElevation:N0} m, una sola provincia por cordillera) no se pueden reclamar. Las tropas cruzan el hielo y las cumbres, despacio.",
            "- Construye granjas y aserraderos, y una ciudad nueva donde haya 500 habitantes.",
            "- Envía colonos desde una ciudad para fundar otras más lejos.",
            "## Consejo",
            "Vigila la comida en la barra superior: si se acaba, la gente muere de hambre y la moral se hunde.",
        ]),
        ("Población y moral",
        [
            "Cada provincia tiene habitantes, moral (0 a 100) y fertilidad. Cada una tiene sus propios nacimientos según su fertilidad, sus habitantes y la tierra que tiene, mientras haya comida y sitio; las ciudades crecen el doble de rápido. La población crece despacio (unos pocos por ciento al año), y cada era la tierra alimenta a más gente: el doble en la Medieval, ocho veces más en la Moderna.",
            $"La comida almacenada se estropea: cada día se pierde el {GameRules.FoodSpoilage:P0} de lo guardado.",
            "## Moral",
            $"- Sube con la ciudad (+{GameRules.CityMood:0}), la capital (+{GameRules.CapitalMood:0}), las reservas de comida, las fiestas (+{GameRules.FestivalMood:0} durante {GameRules.FestivalDays} días), templos, anfiteatros y avances.",
            $"- Baja con la distancia a la capital (hasta -{GameRules.MaxDistanceMoodPenalty:0}), el hacinamiento, el hambre ({GameRules.StarvingMood:0}), la ocupación enemiga y la cultura extranjera.",
            $"- Por debajo de {GameRules.UnrestMood:0} la provincia está descontenta y no paga impuestos. Una moral alta hace trabajar más.",
            "## Cultura y rebelión",
            $"- La gente conserva la cultura de la nación que la pobló. Bajo otro dueño pierde hasta {GameRules.ForeignCultureMood:0} de moral, menos a medida que se asimila (unos {GameRules.AssimilationYears:0} años, menos con moral alta; los migrantes de tus otras provincias ayudan).",
            $"- Una provincia descontenta sin tropas tuyas dentro se acerca a la rebelión (en {GameRules.RevoltDays / 2:0} a {GameRules.RevoltDays:0} días, antes cuanto peor la moral). Si su gente es de una nación que aún existe, se une a ella; si no, hay una revuelta: muere parte de la gente y arde un edificio.",
            "- Una guarnición (un regimiento en la provincia) detiene la rebelión. El panel de la provincia muestra cómo va.",
            "## Migración",
            "Las ciudades envían gente a tus provincias poco pobladas. Puedes forzar una migración pagando oro, pero los migrantes llegan descontentos.",
        ]),
        ("Economía y recursos",
        [
            "Tus provincias producen comida y madera, y pagan oro en impuestos. Todo va al almacén de la nación (barra superior).",
            "## Yacimientos",
            "- Carbón, hierro, cobre, oro, plata, silicio, petróleo, aluminio y caucho salen de yacimientos: bolsas finitas que se agotan.",
            "- Al empezar solo conoces el cobre, el oro y la plata; los demás los revelan los avances (Minería el carbón, Trabajo del hierro el hierro, Química el caucho...).",
            $"- Un yacimiento rinde al máximo con {GameRules.DepositFullWorkers:N0} habitantes en su provincia. El modo de mapa Recursos los muestra.",
            "## Edificios",
            "En la pestaña Edificios de cada provincia. Granjas, graneros, aserraderos y minas van en cualquier provincia habitada; el resto, solo en ciudades. Cada edificio pide un avance.",
            "## Carreteras y ferrocarriles",
            "- Los construyen tus ingenieros: desde una ciudad o un cuartel general tuyos, pulsa «Construir carretera» en su panel y elige qué otra ciudad o cuartel unir (el más cercano sale elegido).",
            "- La ruta es la que seguiría un ejército, por tu tierra, la que ocupas o la libre; las ciudades por las que pasa quedan unidas también. Solo se pagan los tramos que faltan.",
            "- Cada batallón de ingenieros en la ruta hace un día de trabajo al día; si se van, la obra se para. Se ven en el mapa: la carretera clara, el ferrocarril oscuro con traviesas.",
            $"- Por ellas se marcha más deprisa y llega el suministro: a todo lo que unen a tus ciudades y, desde ahí, hasta {MilitaryRules.SupplyRangeHours / 24:0} días de marcha.",
        ]),
        ("Ciudades",
        [
            "Las ciudades producen ciencia, crecen más deprisa, entrenan tropas y construyen los mejores edificios.",
            $"- Con colonos: «Fundar ciudad» en una provincia libre o tuya.",
            $"- Sin colonos: en la pestaña Edificios de una provincia tuya con al menos {GameRules.CityBuildingPopulation} habitantes aparece «Ciudad» ({GameRules.CityCost}, {GameRules.CityBuildingDays} días).",
            "- No puede haber dos ciudades juntas. Tú eliges el nombre.",
        ]),
        ("Ciencia",
        [
            "La ciencia de tus ciudades avanza en tres ramas a la vez: Economía, Sociedad y Militar. En la pestaña Ciencia (N) eliges qué investigar en cada una.",
            "## Prioridades",
            $"- Cada rama tiene una prioridad de 0 a {GameRules.MaxResearchPriority}: la ciencia se reparte en proporción.",
            "- Una rama sin nada elegido cede su parte a las demás; si ninguna investiga, la ciencia se guarda para el siguiente avance que elijas.",
            "## Niveles y eras",
            "- Cada nivel se abre al conocer uno de los avances del nivel anterior de su rama. Algunos avances piden otros concretos.",
            "- Los niveles se agrupan en eras: Antigüedad, Clásica, Medieval, Descubrimientos, Industrial y Moderna. Arriba de la pestaña hay un botón por era.",
            $"- Cada nación vecina que ya conoce un avance te lo abarata un {GameRules.NeighbourResearchDiscount:P0}.",
            "## Instituciones",
            $"- Cada era nueva tiene una institución (Urbanismo, Feudalismo, Humanismo, Industrialización, Electrificación) que nace en algún lugar del mundo y se extiende de provincia en provincia.",
            $"- Tu nación la adopta cuando la tiene la mitad de tu población, o antes pagando oro. Da un bonus; mientras no la adoptes, los avances de su era cuestan un {GameRules.InstitutionPenalty:P0} más.",
            "- El modo de mapa Instituciones muestra por dónde van.",
        ]),
        ("Ejército",
        [
            "Las unidades de combate se forman con batallones entrenados en las ciudades (pestaña Ejército de la provincia). Los hombres salen de la ciudad.",
            "## Cuartel y taller",
            "- Solo las provincias con cuartel entrenan tropas de combate. Exploradores, ingenieros, colonos y cuarteles generales se forman en cualquier ciudad; los barcos, en los puertos.",
            "- Las máquinas de guerra (catapultas, cañones, artillería de campaña, artillería pesada, tanques y bombarderos) no salen del cuartel sino del taller, que llega con la Maquinaria de asedio. Una plantilla que mezcla soldados y máquinas pide los dos.",
            "- Con la Industrialización, tus talleres pasan a ser fábricas: siguen construyendo las máquinas de guerra y además dan +50 % de madera y de yacimientos. Desde entonces se construyen fábricas en lugar de talleres.",
            "- El cuartel, el taller y la fábrica se pueden levantar en cualquier provincia tuya, tenga ciudad o no: una provincia sin ciudad con uno de ellos entrena tropas (pestaña Ejército) y siempre conserva algunos habitantes.",
            $"- Los avances militares que estudian una tropa (Arcos mejorados, Cría caballar, Talleres de asedio...) hacen que el cuartel o el taller la entrene un {MilitaryRules.TechTrainingSpeed:P0} antes, y se suman. Arcos mejorados, por ejemplo, solo acelera a arqueros, carros de arqueros y ballesteros.",
            "## Organización",
            $"- Cada unidad se llama por su tamaño: Regimiento (1 a 3 batallones), Brigada (4 a 6) y División (7 a {MilitaryRules.MaxBattalionsPerUnit}). Son las que se mueven y combaten.",
            "- Diseña plantillas en la pestaña Plantillas de la nación para entrenar unidades enteras de golpe.",
            "- El botón «Editar unidad» de su panel abre una ventana para renombrarla, separar varios batallones a la vez, unirla con otras de la provincia y elegir su oficial.",
            "- Por encima están los cuarteles generales: Cuerpo, Ejército y Grupo de ejércitos. Dan un bonus en combate a las unidades bajo su mando que estén a su alcance.",
            "## Mantenimiento",
            $"- Cada día, batallones, barcos y cuarteles cuestan un {MilitaryRules.UpkeepGoldShare:P0} de su oro y un {MilitaryRules.UpkeepResourceShare:P0} de sus demás recursos (la madera no).",
            "- Si no hay con qué pagar, las tropas pierden organización, desertan y no se recuperan.",
            "## Oficiales y experiencia",
            $"- Recluta oficiales con oro ({MilitaryRules.OfficerCost:0}) en la ventana de edición de una unidad: van a la reserva de tu nación y desde ahí los pones al mando.",
            "- Su rango va con el tamaño de lo que mandan: Coronel (regimiento), Brigadier (brigada), General de división (división), Teniente general (cuerpo), General (ejército) y Mariscal (grupo de ejércitos). Ascienden solos cuando su unidad crece.",
            "- Cada oficial tiene una o dos virtudes (ofensivo, defensivo, organizador, táctico, marchador, intendente), que mejoran con sus estrellas, y a veces un defecto (timorato, temerario, desorganizado, indeciso, lento, corrupto).",
            "- El oficial de una unidad de combate le aplica sus rasgos; el general de un cuartel, a las unidades bajo su mando que estén a su alcance.",
            $"- Tienen de 1 a {Officer.MaxSkill} estrellas y ganan una cada {Officer.VictoriesPerStar} victorias. Si su unidad es destruida en combate, caen con ella; si la relevas o la unes a otra, vuelven a la reserva.",
            $"- Los batallones ganan experiencia combatiendo (Novato, Regular, Veterano, Élite): hasta +{MilitaryRules.ExperienceBonus:P0} de fuego. Los reclutas nuevos la diluyen.",
            "## Suministro y combate",
            "- Las tropas se abastecen desde tus ciudades y por tus carreteras y ferrocarriles, a través de tierra propia o libre; sin suministro pierden hombres y organización.",
            "## Estaciones",
            $"- Lejos del trópico, en invierno la nieve frena a las tropas (hasta el doble de tiempo) y el frío se lleva hasta un {GameRules.WinterAttrition:P1} de sus hombres al día, salvo si se refugian en una de tus ciudades. De diciembre a febrero es invierno en el norte y verano en el sur.",
            "- En primavera y otoño, el barro las frena algo menos. El desierto desgasta todo el año.",
            "- La fecha de arriba dice la estación en tu capital; el panel de cada provincia, la de allí. El mapa de terreno se cubre de nieve en invierno.",
            "- Mover una unidad a una provincia enemiga con tropas la ataca; sin tropas, la ocupa. Cada hora ambos bandos se dañan; el que pierde la organización se retira.",
            $"- Frente: solo combaten a la vez los mejores batallones que caben en él ({MilitaryRules.FrontWidth(Biome.Grassland)} en llano, {MilitaryRules.FrontWidth(Biome.HighMountains)} en alta montaña); el resto espera en reserva.",
            "- La artillería, la aviación y los ingenieros van detrás del frente (la mitad de ancho) y reciben menos daño.",
            $"- Si el atacante lleva ingenieros, el río no le frena y la ventaja del terreno del defensor se queda en la {MilitaryRules.EngineeredTerrainDefense:P0}.",
            $"- Armas combinadas: cada tipo de tropa distinto (infantería, caballería, artillería, blindados, aviación, ingenieros) suma +{MilitaryRules.CombinedArmsBonus:P0} de fuego, hasta +{MilitaryRules.MaxCombinedArmsBonus:P0}.",
            "- Defender es más fácil en montañas, bosques, ríos y detrás de murallas o castillos. La caballería rinde menos en terreno difícil.",
            $"- Asedios: una provincia con murallas o castillo no se ocupa al entrar; hay que sitiarla {MilitaryRules.SiegeDaysPerDefense / 2:0} días (murallas) o {MilitaryRules.SiegeDaysPerDefense:0} (castillo). Catapultas, cañones y artillería lo acortan. Si los sitiadores se van, el asedio se levanta; mientras sitian, reciben suministro si la provincia linda con una tuya abastecida.",
        ]),
        ("Flotas y mar",
        [
            "Las tropas no cruzan el mar solas: necesitan barcos. Solo los aviones vuelan sobre él.",
            "## Puertos y barcos",
            "- Construye un Puerto (Navegación a vela) en una ciudad con costa. Allí se construyen los barcos, y cada uno forma una flota.",
            "- Trirremes, galeones, acorazados, destructores y portaaviones combaten; los barcos de transporte llevan tropas. Los más avanzados piden un Dique seco.",
            "- Las flotas navegan por el mar costero con Navegación a vela y por el océano con Cartografía. Se reparan en puerto.",
            "## Transportar tropas",
            "- Embarca una unidad con el botón «Embarcar en...» de su panel o con clic derecho sobre una flota tuya con transportes en el mar de al lado.",
            "- Mueve la flota y, con la unidad embarcada seleccionada, haz clic derecho en la costa para desembarcar. En tierra enemiga sin tropas, la ocupa.",
            "- Las flotas enemigas que se encuentran combaten; la que se rompe huye o se hunde con lo que lleva.",
        ]),
        ("Diplomacia",
        [
            "En la pestaña Diplomacia de la nación declaras la guerra, propones la paz, firmas alianzas y haces regalos.",
            "- Tus ejércitos solo entran en tierras de naciones con las que estás en guerra.",
            "- La puntuación de guerra (de -100 a 100) suma lo que ocupas del enemigo, resta lo que te ocupa y cuenta las batallas ganadas y perdidas. Las ciudades y la capital valen más.",
            "- Paz blanca: las provincias ocupadas vuelven a sus dueños. Los rivales la aceptan si la guerra les va mal o se alarga.",
            "- Exigir: te quedas con lo que ocupas, si la puntuación lo paga. Si te quedas con todo, la nación desaparece.",
            "- Ceder: entregas lo que te ocupan para acabar una guerra perdida.",
            $"- Tras cada paz hay una tregua de {GameRules.TruceDays} días: ninguno de los dos puede declarar la guerra al otro.",
            $"- Opinión: cada nación piensa algo de las demás (de -100 a 100), por lo que ve (frontera, enemigos o rivales comunes, su gente bajo otro dueño) y por lo que recuerda (guerras, provincias quitadas, regalos), que se olvida con el tiempo. La columna Opinión dice qué piensan de ti y por qué.",
            $"- Alianzas: si uno de los aliados es atacado, los demás entran en la guerra, y sus ejércitos cruzan las tierras del otro. Los rivales aceptan si su opinión de ti llega a {GameRules.AllianceAcceptOpinion:0}; un regalo (un mes de tus ingresos de oro) la sube {GameRules.GiftOpinion:0}.",
            "- Los rivales atacan a vecinos que creen poder vencer, más aún si se han quedado sin tierra libre, si el vecino ya está en otra guerra o si gobierna gente de su cultura.",
            "- Con puertos y transportes, también cruzan el mar: reúnen tropas en su mayor puerto, embarcan y desembarcan en tu costa peor defendida. Con Navegación a vela llegan a costas cercanas; con Cartografía, al otro lado del océano.",
        ]),
        ("Mapa",
        [
            "Los botones de abajo (o Tab) cambian el modo de mapa:",
            "- Terreno y Político: el mundo y quién es dueño de cada provincia.",
            "- Población, Moral y Fertilidad: el estado de cada provincia habitada.",
            "- Recursos: los yacimientos que conoces, con un filtro por recurso.",
            "- Instituciones: por dónde se han extendido.",
            "- Cultura: de qué nación es la gente de cada provincia. Si el color no es el de la franja de su frontera, la gente es extranjera.",
            "Al pasar el ratón por una provincia verás sus datos. Las espadas rojas marcan batallas, en tierra o en el mar: haz clic en ellas para ver la batalla en detalle.",
        ]),
        ("Partida",
        [
            "- El menú (Esc o botón Menú) pausa el juego, guarda la partida y muestra el historial de versiones.",
            "- Música y sonido: en el menú (y en la pantalla inicial) hay un botón para cada uno; cada pulsación sube el volumen y, después del máximo, lo apaga. La música cambia con la era y cuando estás en guerra.",
            "- La dificultad se elige al empezar: cambia cuántos yacimientos hay y su tamaño, los recursos iniciales y lo que producen los rivales.",
            "- Los rivales del ordenador se expanden, investigan, construyen y hacen la guerra por su cuenta.",
        ]),
    ];

    /// <summary>Every topic title and line of text, for checking them.</summary>
    public static IEnumerable<string> AllText => All.SelectMany(t => t.Text.Prepend(t.Title));

    /// <summary>A topic's text as headings, bullets and paragraphs.</summary>
    public static IReadOnlyList<MarkupLine> Lines(int topic) => All[topic].Text.Select(Markup.Parse).ToList();
}
